services:
    api-backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/app
        restart: always
        container_name: api_backend
        networks:
            - notification_network
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
            worker:
                condition: service_healthy

    worker:
        build: 
            context: ./backend
            dockerfile: ./redis_worker/Dockerfile
        env_file:
            - .env
        ports:
            - "8675:8675"
        volumes:
            - ./backend:/worker
        restart: always
        container_name: worker
        networks:
            - notification_network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8675/healthcheck"]
        depends_on:
            redis:
                condition: service_healthy

    db:
        image: postgres:17-alpine
        container_name: postgres_db
        restart: always
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/data/postgres
        volumes:
            - ./data/postgres_data:/data/postgres
        networks:
            - notification_network
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:8-alpine
        container_name: redis_cache
        restart: unless-stopped
        ports:
        - "6753:6379"
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - ./data/redis_data:/data
        networks:
            - notification_network
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    notification_network:
        driver: bridge